'use strict';
const $=s=>document.querySelector(s),app=$('#app'),modal=$('#modal');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v||0).toLocaleString('vi-VN')+' đ';
const date=v=>new Date(Number(v)).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'});
const day=v=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(Number(v)));
const id=()=>Array.from(crypto.getRandomValues(new Uint8Array(16)),n=>n.toString(16).padStart(2,'0')).join('');
let user=null,movies=[],cinemas=[],page=0,currentShow=0,seatMap=null,selected=new Set(),paymentKey=null,busy=false,polling=false,paymentConfig={},serverOffset=0;
function notice(text){$('#message').textContent=text;}
async function post(path,data={}){const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data),signal:AbortSignal.timeout(20000)});const v=await r.json();if(!r.ok){if(r.status===401){user=null;login();}throw Error(v.message||'Lỗi kết nối');}return v;}
const api=(type,data={})=>post('request',{type,data});
const button=(text,action,key='',primary=false)=>`<button ${primary?'class="primary"':''} data-action="${action}" data-id="${esc(key)}">${esc(text)}</button>`;
function nav(){ $('#nav').innerHTML=user?button('Phim & lịch chiếu','home')+button('Vé & thanh toán','tickets')+button('Ưu đãi & điểm','rewards')+(user.role==='ADMIN'?button('Quản trị','admin'):'')+button('Đăng xuất','logout'):''; }
function login(){page++;currentShow=0;nav();$('#connection').textContent='Chưa kết nối';app.innerHTML=`<section class="panel login"><span class="tag">VKU CINEMA · TCP/IP</span><h1>Hẹn nhau ở rạp.</h1><p>Đăng nhập để chọn ghế, nhận ưu đãi và tích điểm.</p><form id="login-form"><label>Tên đăng nhập<input name="username" autocomplete="username" required maxlength="30"></label><label>Mật khẩu<input name="password" type="password" autocomplete="current-password" required maxlength="128"></label><button class="primary">Kết nối & đăng nhập</button></form><details><summary>Tạo tài khoản</summary><form id="register-form"><label>Tên hiển thị<input name="displayName" required maxlength="60"></label><label>Tên đăng nhập<input name="username" required maxlength="30"></label><label>Mật khẩu (8–128 ký tự)<input type="password" name="password" required minlength="8" maxlength="128"></label><button>Đăng ký</button></form></details></section>`;}
async function leave(){page++;if(currentShow){const show=currentShow;currentShow=0;await api('RELEASE_SEATS',{showId:show}).catch(()=>{});await api('UNSUBSCRIBE_SHOW').catch(()=>{});}selected.clear();paymentKey=null;seatMap=null;}
function safeUrl(value){try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)?u.href:'';}catch{return '';}}
function fallbackPoster(m){return 'data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 600"><defs><linearGradient id="g" x2="1" y2="1"><stop stop-color="#263759"/><stop offset="1" stop-color="#6d243b"/></linearGradient></defs><rect width="400" height="600" fill="url(#g)"/><circle cx="280" cy="190" r="130" fill="#f6c84b" opacity=".18"/><path d="M0 450L170 260L400 520V600H0" fill="#111521"/><text x="30" y="60" fill="#f6c84b" font-family="sans-serif" font-size="20">VKU CINEMA</text><text x="30" y="540" fill="white" font-family="sans-serif" font-size="24">${esc(m.title).slice(0,28)}</text></svg>`);}
function poster(m){const src=safeUrl(m.poster_url)||fallbackPoster(m);return `<article class="poster"><img ${src?`src="${esc(src)}"`:''} data-media="${esc(m.poster_url)}" alt="Poster ${esc(m.title)}" loading="lazy"><button class="play" data-action="trailer" data-id="${m.id}" ${m.trailer_url?'':'disabled'}>${m.trailer_url?'▶ Trailer':'Chưa có trailer'}</button><div class="copy"><span class="tag">${esc(m.screening_label)}</span><h2>${esc(m.title)}</h2><p>${esc(m.genre)} · ${m.duration_minutes} phút · ${esc(m.age_rating)}</p><small>Khởi chiếu: ${esc(m.release_date||'Chưa công bố')}<br>${esc(m.release_label||'')}</small><p>${button('Lịch chiếu','movie',m.id,true)}</p></div></article>`;}
async function hydrate(){for(const img of document.querySelectorAll('[data-media^="asset:"]')){try{const v=await api('GET_IMAGE',{id:img.dataset.media.slice(6)});if(img.isConnected)img.src=`data:${v.mimeType||v.mime_type};base64,${v.data}`;}catch{img.alt+=' (chưa tải được ảnh)';}}}
async function home(){await leave();const version=page;app.innerHTML='<p>Đang tải danh mục…</p>';const data=await Promise.all([api('GET_MOVIES'),api('GET_CINEMAS'),api('GET_PAYMENT_CONFIG')]);if(page!==version)return;[movies,cinemas,paymentConfig]=data;app.innerHTML=`<section class="hero"><span class="tag">ĐIỆN ẢNH · TRẢI NGHIỆM CÙNG NHAU</span><h1>Chọn phim hay.<br>Giữ chỗ hôm nay.</h1><p>Chào ${esc(user.display_name)}. Lịch chiếu và ghế được cập nhật từ máy chủ.</p></section><div class="filters"><input id="search" aria-label="Tìm phim" placeholder="Tìm phim, thể loại, diễn viên…"><select id="genre" aria-label="Thể loại"><option value="">Tất cả thể loại</option>${[...new Set(movies.flatMap(m=>(m.genres||[]).map(g=>g.name)))].map(g=>`<option>${esc(g)}</option>`).join('')}</select><select id="status" aria-label="Trạng thái"><option value="">Tất cả phim</option><option>Đang chiếu</option><option>Sắp chiếu</option><option>Đã ngừng chiếu</option></select></div><div id="cards" class="grid"></div>`;const render=()=>{const q=$('#search').value.toLocaleLowerCase('vi');$('#cards').innerHTML=movies.filter(m=>(m.title+' '+m.genre+' '+m.cast_names).toLocaleLowerCase('vi').includes(q)&&(!$('#genre').value||(m.genres||[]).some(g=>g.name===$('#genre').value))&&(!$('#status').value||m.screening_label===$('#status').value)).map(poster).join('')||'<p>Không có phim phù hợp.</p>';void hydrate();};$('#search').oninput=render;$('#genre').onchange=render;$('#status').onchange=render;render();}
function trailer(movieId){const m=movies.find(m=>m.id===Number(movieId));if(!m?.trailer_url)return;const url=safeUrl(m.trailer_url);if(!url)throw Error('Link trailer không hợp lệ.');const u=new URL(url);let videoId='';if(u.hostname==='youtu.be')videoId=u.pathname.slice(1);if(['youtube.com','www.youtube.com','m.youtube.com'].includes(u.hostname))videoId=u.searchParams.get('v')||u.pathname.split('/').at(-1);$('#modal-body').innerHTML=`<h2>${esc(m.title)} · Trailer</h2>`+(/^[A-Za-z0-9_-]{11}$/.test(videoId)?`<iframe src="https://www.youtube-nocookie.com/embed/${videoId}" title="Trailer" allow="fullscreen; encrypted-media" allowfullscreen></iframe>`:/\.(mp4|webm)(\?|$)/i.test(url)?`<video controls src="${esc(url)}"></video>`:`<p>Trailer được mở từ nguồn do rạp cung cấp.</p><a class="button" href="${esc(url)}" target="_blank" rel="noopener noreferrer">Mở trailer</a>`);modal.showModal();}
async function detail(movieId){await leave();const version=page,m=movies.find(m=>m.id===Number(movieId));if(!m)return;const shows=await api('GET_SHOWTIMES',{movieId:m.id});if(page!==version)return;app.innerHTML=`${button('← Danh mục','home')}<section class="details panel"><img src="${esc(safeUrl(m.poster_url)||fallbackPoster(m))}" data-media="${esc(m.poster_url)}" alt="${esc(m.title)}"><div><span class="tag">${esc(m.screening_label)}</span><h1>${esc(m.title)}</h1><p>${esc(m.description)}</p><p>${esc(m.genre)} · ${m.duration_minutes} phút · ${esc(m.age_rating)}</p><p>Khởi chiếu ${esc(m.release_date||'Chưa công bố')} · ${esc(m.release_label||'')}<br>Đạo diễn: ${esc(m.director)}<br>Diễn viên: ${esc(m.cast_names)}</p>${button('▶ Trailer','trailer',m.id)}</div></section><h2>Lịch chiếu</h2><div class="filters"><select id="cinema"><option value="">Tất cả rạp</option>${cinemas.map(c=>`<option value="${c.id}">${esc(c.area_name+' · '+c.name)}</option>`).join('')}</select><input type="date" id="show-day" aria-label="Ngày chiếu"><button id="clear-filter">Bỏ lọc</button></div><div id="shows" class="list"></div>`;const render=()=>{$('#shows').innerHTML=shows.filter(s=>(!$('#cinema').value||String(s.cinema_id)===$('#cinema').value)&&(!$('#show-day').value||day(s.starts_at)===$('#show-day').value)).map(s=>`<article class="row"><div><h2>${esc(s.cinema_name)}</h2><p>${esc(s.address)} · ${esc(s.phone)}<br>Giờ hoạt động ${esc(s.opens_at)}–${esc(s.closes_at)}<br>${date(s.starts_at)} → ${date(s.ends_at)} · ${esc(s.room_name)}</p></div><div><span class="money">${money(s.price_vnd)}</span><p>${button('Chọn ghế','show',s.id,true)}</p></div></article>`).join('')||'<p class="empty">Chưa có suất chiếu phù hợp.</p>';};$('#cinema').onchange=render;$('#show-day').onchange=render;$('#clear-filter').onclick=()=>{$('#cinema').value='';$('#show-day').value='';render();};render();void hydrate();}
async function openShow(showId){await leave();currentShow=Number(showId);const version=page;const map=await api('SUBSCRIBE_SHOW',{showId:currentShow});if(page!==version)return;app.innerHTML=`${button('← Danh mục','home')}<h1>${esc(map.show.title)}</h1><p>${date(map.show.starts_at)} · ${esc(map.show.cinema_name)} / ${esc(map.show.room_name)}</p><div class="screen">MÀN HÌNH</div><div id="seats" class="seats"></div><p>Vàng: bạn chọn · Viền xanh: bạn giữ · Đỏ: đã bán · Nâu: người khác giữ</p><section class="panel checkout"><div id="selection"></div><p id="countdown"></p><label>Mã giảm giá<input id="coupon" maxlength="32" placeholder="Nhập mã ưu đãi"></label><div class="row">${button('Giữ ghế 5 phút','hold','',true)}${button('Bỏ giữ','release')}${button('Tính tiền','quote')}</div><div id="quote"></div></section>`;applyMap(map);}
function applyMap(map){if(!currentShow||map.show.id!==currentShow)return;if(seatMap&&map.revision<seatMap.revision)return;seatMap=map;serverOffset=map.serverTime-Date.now();const valid=new Set(map.seats.filter(s=>s.status==='AVAILABLE'||s.is_mine).map(s=>s.seat_label));selected=new Set([...selected].filter(s=>valid.has(s)));renderSeats();}
function renderSeats(){if(!$('#seats')||!seatMap)return;const rows=new Map();for(const s of seatMap.seats){const row=s.seat_label[0];if(!rows.has(row))rows.set(row,[]);rows.get(row).push(s);}$('#seats').innerHTML=[...rows.values()].map(row=>`<div class="seat-row">${row.map(s=>`<button class="seat ${s.is_mine?'mine':s.status.toLowerCase()} ${selected.has(s.seat_label)?'selected':''}" data-action="seat" data-id="${s.seat_label}" aria-pressed="${selected.has(s.seat_label)}" ${busy||s.status!=='AVAILABLE'&&!s.is_mine?'disabled':''}>${s.seat_label}</button>`).join('')}</div>`).join('');$('#selection').textContent=`Ghế: ${[...selected].join(', ')||'chưa chọn'} · Tạm tính ${money(selected.size*seatMap.show.price_vnd)}`;countdown();}
function countdown(){if(!$('#countdown')||!seatMap)return;const mine=seatMap.seats.filter(s=>s.is_mine),until=Math.max(0,...mine.map(s=>s.hold_until));const seconds=Math.max(0,Math.floor((until-Date.now()-serverOffset)/1000));$('#countdown').textContent=seconds?`Còn ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')} giữ ghế`:'Chọn ghế rồi bấm Giữ ghế.';}
async function quote(){if(!selected.size)throw Error('Chọn ghế trước.');const data={showId:currentShow,seats:[...selected],coupon:$('#coupon').value};const q=await api('QUOTE_BOOKING',data);$('#quote').innerHTML=`<p>Giá gốc ${money(q.subtotal)} · Giảm ${money(q.discount)}</p><p class="money">${money(q.total)}</p><p>Nhận ${q.pointsEarned} điểm khi thành công</p>${button(paymentConfig.enabled?'Tạo QR payOS':'Xác nhận DEMO (không thu tiền)','pay','',true)}`;}
async function pay(){const data={showId:currentShow,seats:[...selected],coupon:$('#coupon').value,requestId:paymentKey||(paymentKey=id())};const q=await api('QUOTE_BOOKING',data);if(!confirm(`Thanh toán ${money(q.total)}${paymentConfig.enabled?' qua QR payOS?':' mô phỏng, không thu tiền?'}`))return;const result=await api(paymentConfig.enabled?'CREATE_PAYMENT':'CONFIRM_BOOKING',data);paymentKey=null;if(paymentConfig.enabled)paymentDialog(result);else notice('Đặt vé thành công: '+result.code);await tickets();}
function paymentDialog(p){const url=safeUrl(p.checkoutUrl);$('#modal-body').innerHTML=`<h2>Thanh toán ${esc(p.id)}</h2><p class="money">${money(p.amount)}</p><p>Trạng thái: <strong>${esc(p.status)}</strong><br>Hạn: ${date(p.expires_at)}</p>${url.startsWith('https://pay.payos.vn/')&&['PENDING','CREATING'].includes(p.status)&&p.expires_at>Date.now()+serverOffset?`<a class="button" href="${esc(url)}" target="_blank" rel="noopener noreferrer">Mở mã QR chính thức trên payOS</a>`:''}<p>Chỉ PAID mới được xuất vé. REVIEW: liên hệ rạp để đối soát/hoàn tiền. Không chuyển tiền sau hạn.</p>${button('Kiểm tra giao dịch','payment',p.id)}`;if(!modal.open)modal.showModal();}
async function tickets(){await leave();const version=page;const [bookings,payments]=await Promise.all([api('GET_MY_TICKETS'),api('GET_MY_PAYMENTS')]);if(page!==version)return;app.innerHTML=`<h1>Vé & thanh toán</h1>${button('Tải lại','tickets')}<h2>Vé của tôi</h2><div class="list">${bookings.map(b=>`<article><span class="tag">${esc(b.code)} · ${esc(b.status)}</span><h2>${esc(b.title)}</h2><p>${date(b.starts_at)} · ${esc(b.room_name)} · Ghế ${esc(b.seats)}</p><strong>${money(b.total_vnd)}</strong><p>${esc(b.payment_method)}${b.payment_method==='DEMO'?' · Vé mô phỏng':''}</p>${b.status==='CONFIRMED'&&b.payment_method==='DEMO'?button('Huỷ vé demo','cancel',b.id):''}</article>`).join('')||'<p>Chưa có vé.</p>'}</div><h2>Giao dịch QR</h2><div class="list">${payments.map(p=>`<article class="row"><div>#${p.id} · ${money(p.amount)} · ${esc(p.status)}<p>${date(p.created_at)}</p></div>${button('Xem / đối soát','payment',p.id)}</article>`).join('')||'<p>Chưa có giao dịch QR.</p>'}</div>`;}
async function rewards(){await leave();const version=page;const [loyalty,promos]=await Promise.all([api('GET_LOYALTY'),api('GET_PROMOTIONS')]);if(page!==version)return;app.innerHTML=`<section class="hero"><span class="tag">THÀNH VIÊN VKU</span><h1>${loyalty.points} điểm</h1><p>Mỗi 10.000đ sau giảm giá nhận 1 điểm. Huỷ vé sẽ trừ lại số điểm đã cộng. Điểm hiện dùng để ghi nhận thành viên, chưa quy đổi thành tiền.</p></section><h2>Ưu đãi đang diễn ra</h2><div class="grid">${promos.map(p=>`<article><h2>${esc(p.code)}</h2><span class="money">Giảm ${p.percent}%</span><p>Tối đa ${money(p.max_discount)} · Đơn từ ${money(p.min_total)}<br>Đến ${date(p.ends_at)}<br>${p.per_user} lượt/khách · Tổng hạn mức ${p.quota} lượt</p></article>`).join('')||'<p>Hiện chưa có mã giảm giá.</p>'}</div><h2>Lịch sử tích điểm</h2>${table(loyalty.history,['code','points','reason','created_at'])}`;}
function table(rows,keys){return `<div class="table"><table><thead><tr>${keys.map(k=>`<th>${esc(k)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${keys.map(k=>`<td>${esc(k.endsWith('_at')&&typeof r[k]==='number'?date(r[k]):r[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
const adminSchemas={
 PROMOTIONS:{title:'Mã giảm giá',list:'PROMOTIONS',save:'PROMOTION',fields:{code:['Mã','text'],percent:['Giảm %','number',10],max_discount:['Giảm tối đa (đ)','number',50000],min_total:['Đơn tối thiểu','number',0],starts_at:['Bắt đầu','datetime-local'],ends_at:['Kết thúc','datetime-local'],quota:['Tổng lượt','number',100],per_user:['Lượt/khách','number',1],active:['Bật (1) / tắt (0)','number',1]}},
 MOVIES:{title:'Phim & trailer',list:'MOVIES',save:'MOVIE',fields:{id:['ID (0 = thêm mới)','number',0],title:['Tên phim','text'],genre:['Thể loại','text'],duration_minutes:['Thời lượng phút','number',120],age_rating:['Phân loại tuổi','text','P'],description:['Mô tả','text'],poster_url:['URL poster','url'],banner_url:['URL banner','url'],trailer_url:['URL trailer YouTube/MP4','url'],release_date:['Khởi chiếu','date'],end_date:['Ngừng chiếu','date'],director:['Đạo diễn','text'],cast_names:['Diễn viên','text']}},
 SHOWS:{title:'Lịch chiếu',list:'SHOWS',save:'SHOW',fields:{id:['ID (0 = thêm mới)','number',0],movie_id:['ID phim','number'],room_id:['ID phòng','number'],starts_at:['Giờ bắt đầu (Việt Nam)','datetime-local'],price_vnd:['Giá vé','number',75000]}},
 CINEMAS:{title:'Rạp & giờ hoạt động',list:'CINEMAS',save:'CINEMA',fields:{id:['ID (0 = thêm mới)','number',0],name:['Tên rạp','text'],area_id:['ID khu vực','number'],address:['Địa chỉ','text'],phone:['Điện thoại','text'],image_url:['Ảnh rạp','url'],opens_at:['Mở cửa','time','08:00'],closes_at:['Đóng cửa','time','23:59']}}
};
let adminKind='PROMOTIONS',adminRows=[];
async function admin(kind=adminKind){if(user.role!=='ADMIN')return;await leave();adminKind=kind;const version=page;const schema=adminSchemas[kind];adminRows=await api('ADMIN_LIST_'+(schema?.list||kind));if(version!==page)return;app.innerHTML=`<h1>Quản trị rạp</h1><div class="row">${Object.entries(adminSchemas).map(([k,s])=>button(s.title,'admin-tab',k)).join('')}${button('Thanh toán','admin-tab','PAYMENTS')}${button('Phòng','admin-tab','ROOMS')}${button('Khu vực','admin-tab','AREAS')}</div><h2>${schema?.title||esc(kind)}</h2>${schema?`<label>Chọn bản ghi để sửa<select id="edit-record"><option value="">Thêm mới</option>${adminRows.map((r,i)=>`<option value="${i}">${esc(r.code||r.title||r.name||r.id)}</option>`).join('')}</select></label><form id="admin-form" class="panel admin-form">${Object.entries(schema.fields).map(([key,[label,type,value='']])=>`<label>${label}<input name="${key}" type="${type}" value="${esc(value)}" ${['title','name','code'].includes(key)?'required':''}></label>`).join('')}<button class="primary">Lưu trên server</button></form>`:'<p>PAYMENTS: giao dịch REVIEW cần đối soát với payOS; không tự động hoàn tiền.</p>'}${table(adminRows,Object.keys(adminRows[0]||{}).filter(k=>!['description','genres','qrCode','checkoutUrl','cast_names'].includes(k)))}`;if(schema)$('#edit-record').onchange=()=>{const row=adminRows[$('#edit-record').value];for(const [key,[,type,def='']]of Object.entries(schema.fields)){let value=row?.[key]??def;if(type==='datetime-local'&&value)value=new Date(Number(value)+7*3600000).toISOString().slice(0,16);$('#admin-form').elements[key].value=value;}if(kind==='PROMOTIONS')$('#admin-form').elements.code.readOnly=!!row;};}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||busy)return;const action=b.dataset.action,key=b.dataset.id;try{if(action==='seat'){if(selected.has(key))selected.delete(key);else if(selected.size<8)selected.add(key);else throw Error('Tối đa 8 ghế.');paymentKey=null;$('#quote').innerHTML='';renderSeats();return;}if(action==='trailer'){trailer(key);return;}busy=true;b.disabled=true;if(action==='home')await home();if(action==='movie')await detail(key);if(action==='show')await openShow(key);if(action==='hold'){paymentKey=null;applyMap(await api('HOLD_SEATS',{showId:currentShow,seats:[...selected]}));notice('Đã giữ ghế.');}if(action==='release'){selected.clear();paymentKey=null;applyMap(await api('RELEASE_SEATS',{showId:currentShow}));$('#quote').innerHTML='';}if(action==='quote')await quote();if(action==='pay')await pay();if(action==='tickets')await tickets();if(action==='rewards')await rewards();if(action==='payment')paymentDialog(await api('GET_PAYMENT',{paymentId:Number(key)}));if(action==='cancel'&&confirm('Huỷ vé demo này?')){await api('CANCEL_BOOKING',{bookingId:Number(key)});await tickets();}if(action==='admin')await admin();if(action==='admin-tab')await admin(key);if(action==='logout'){await post('logout');user=null;login();}}catch(e){notice(e.message);}finally{busy=false;b.disabled=false;if(currentShow)renderSeats();}});
document.addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;const submit=e.target.querySelector('button[type="submit"],button');if(submit)submit.disabled=true;try{const data=Object.fromEntries(new FormData(e.target));if(e.target.id==='login-form'){const v=await post('login',data);user=v.user;$('#connection').textContent='● TCP '+v.server;nav();await home();notice('Đã kết nối và đăng nhập.');}if(e.target.id==='register-form'){await post('register',data);e.target.reset();notice('Đã tạo tài khoản. Đăng nhập để tiếp tục.');}if(e.target.id==='admin-form'){const schema=adminSchemas[adminKind];for(const [key,[,type]]of Object.entries(schema.fields)){if(type==='number')data[key]=Number(data[key]);if(type==='datetime-local')data[key]=new Date(data[key]+':00+07:00').getTime();}await api('ADMIN_SAVE_'+schema.save,data);await admin();notice('Đã lưu.');}}catch(e){notice(e.message);}finally{busy=false;if(submit)submit.disabled=false;}});
$('#close-modal').onclick=()=>{modal.close();$('#modal-body').innerHTML='';};modal.addEventListener('close',()=>$('#modal-body').innerHTML='');
setInterval(()=>{$('#clock').textContent=date(Date.now());countdown();},1000);
setInterval(async()=>{if(!user||busy||polling)return;polling=true;const version=page,show=currentShow;try{if(show){const map=await api('GET_SEATMAP',{showId:show});if(version===page)applyMap(map);}else await api('PING');$('#connection').textContent='● Đã kết nối TCP · '+new Date().toLocaleTimeString('vi-VN');}catch(e){$('#connection').textContent='● Mất kết nối';notice(e.message);}finally{polling=false;}},4000);
(async()=>{try{const v=await post('session');user=v.user;nav();$('#connection').textContent='● TCP '+v.server;await home();}catch{login();}})();
